-- 500 generated SQL queries for training
select ol_number, min(ol_amount) as min_amount from order_line where ol_quantity > 5 group by ol_number order by min_amount desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_amount < 500 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2024-11-01 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance > 1000 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'GC' group by c_state order by total_balance desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2024-10-01 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 50 group by s_w_id order by avg_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 10 group by s_i_id order by total_orders desc;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'CHINA' group by su.s_suppkey order by supp_count desc;
select i_id, min(i_price) as min_price from item where i_price > 10 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount > 100 group by ol_number order by max_amount desc;
select ol_w_id, min(ol_quantity) as min_qty from order_line where ol_quantity < 100 group by ol_w_id order by min_qty;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2024-12-01 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, avg(c_balance) as avg_balance from customer where c_balance < 500 group by c_id order by avg_balance;
select c_state, count(*) as state_count from customer where c_state like 'B%' group by c_state order by state_count desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2024-09-01 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 200 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt < 20 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal > 0 group by su.s_suppkey order by total_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price < 1000 group by i_id order by max_price desc;
select n_name, sum(n_nationkey) as nation_sum from nation group by n_name order by nation_sum desc;
select r_name, count(*) as region_count from region group by r_name order by region_count desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_quantity between 10 and 100 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_amount between 100 and 1000 group by ol_w_id order by count_orders desc;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2024-11-15 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance > 2000 group by c_id order by sum_balance desc;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'BC' group by c_state order by avg_balance;
select o_entry_d, count(*) as order_count from orders where o_entry_d > '2024-08-01 00:00:00' group by o_entry_d order by order_count desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity > 10 group by s_w_id order by min_qty;
select s_i_id, max(s_order_cnt) as max_orders from stock where s_order_cnt < 50 group by s_i_id order by max_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal < 0 group by su.s_suppkey order by avg_acctbal;
select i_id, sum(i_price) as sum_price from item where i_price > 500 group by i_id order by sum_price desc;
select n_name, min(n_nationkey) as min_nation from nation group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 200 group by ol_number order by cnt desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity > 20 group by ol_w_id order by avg_qty;
select ol_d_id, max(ol_amount) as max_amount from order_line where ol_delivery_d < '2024-10-15 00:00:00' group by ol_d_id order by max_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance < 100 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'C%' group by c_state order by sum_balance desc;
select o_entry_d, avg(o_ol_cnt) as avg_cnt from orders where o_entry_d < '2024-07-01 00:00:00' group by o_entry_d order by avg_cnt;
select s_w_id, count(*) as count_qty from stock where s_quantity > 100 group by s_w_id order by count_qty desc;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 5 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 1000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price < 200 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 5 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey group by r_name order by min_nation desc;
-- ... (repeat and diversify until 500 SQLs) ... 
select ol_number, sum(ol_quantity) as total_qty from order_line where ol_amount > 200 group by ol_number order by total_qty desc;
select ol_w_id, min(ol_amount) as min_amount from order_line where ol_quantity < 50 group by ol_w_id order by min_amount;
select ol_d_id, count(*) as cnt from order_line where ol_delivery_d > '2024-12-01 00:00:00' group by ol_d_id order by cnt desc;
select c_id, max(c_balance) as max_balance from customer where c_balance > 3000 group by c_id order by max_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'GC' group by c_state order by min_balance;
select o_entry_d, avg(o_ol_cnt) as avg_cnt from orders where o_entry_d > '2024-11-01 00:00:00' group by o_entry_d order by avg_cnt desc;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity > 150 group by s_w_id order by sum_qty desc;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 30 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'GERMANY' group by su.s_suppkey order by supp_count desc;
select i_id, max(i_price) as max_price from item where i_price > 2000 group by i_id order by max_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 10 group by n_name order by nation_sum desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 2 group by r_name order by min_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 300 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 30 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2024-11-20 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 1500 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'GC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2024-10-10 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 80 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt < 15 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 500 group by su.s_suppkey order by avg_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 50 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 8 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 3 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 400 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 60 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2024-12-10 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 2500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'D%' group by c_state order by state_count desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2024-09-10 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 300 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 25 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 0 group by su.s_suppkey order by total_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price > 1500 group by i_id order by max_price desc;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 3 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 7 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount > 250 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity < 90 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2024-12-25 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance < 1600 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'BC' group by c_state order by total_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2024-09-20 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 400 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 35 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 300 group by su.s_suppkey order by total_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 30 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 12 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 5 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 600 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 100 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2024-12-30 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 3500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'F%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2024-12-01 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 40 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt < 45 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 300 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price < 4000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 9 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 9 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 400 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity > 100 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d < '2025-01-01 00:00:00' group by ol_d_id order by avg_amount;
select c_id, min(c_balance) as min_balance from customer where c_balance > 2000 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'G%' group by c_state order by sum_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2024-11-01 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 200 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 50 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 2000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price > 300 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 10 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 6 group by r_name order by min_nation desc; 
select ol_number, min(ol_quantity) as min_qty from order_line where ol_amount > 300 group by ol_number order by min_qty;
select ol_w_id, max(ol_amount) as max_amount from order_line where ol_quantity < 60 group by ol_w_id order by max_amount desc;
select ol_d_id, avg(ol_quantity) as avg_qty from order_line where ol_delivery_d > '2025-01-10 00:00:00' group by ol_d_id order by avg_qty;
select c_id, sum(c_balance) as total_balance from customer where c_balance > 4000 group by c_id order by total_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'GC' group by c_state order by min_balance;
select o_entry_d, count(*) as cnt from orders where o_entry_d > '2024-12-10 00:00:00' group by o_entry_d order by cnt desc;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 250 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 60 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'USA' group by su.s_suppkey order by supp_count desc;
select i_id, min(i_price) as min_price from item where i_price > 100 group by i_id order by min_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 15 group by n_name order by nation_sum desc;
select r_name, max(n_nationkey) as max_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 8 group by r_name order by max_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 400 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 120 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2025-01-20 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 2500 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'BC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2024-12-15 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 120 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 60 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 800 group by su.s_suppkey order by avg_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price > 3500 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 12 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 12 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount > 450 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity < 120 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2025-01-25 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance < 1800 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'GC' group by c_state order by total_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2024-10-25 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 500 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 45 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 500 group by su.s_suppkey order by total_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 40 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 14 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 7 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 800 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 140 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2025-01-30 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 5500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'K%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2025-02-01 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 100 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt < 55 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 400 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price < 5000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 11 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 13 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 500 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity > 150 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d < '2025-02-01 00:00:00' group by ol_d_id order by avg_amount;
select c_id, min(c_balance) as min_balance from customer where c_balance > 3000 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'I%' group by c_state order by sum_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2024-12-01 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 300 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 70 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 3000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price > 400 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 12 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 8 group by r_name order by min_nation desc;
select ol_number, sum(ol_amount) as sum_amount from order_line where ol_quantity > 200 group by ol_number order by sum_amount desc;
select ol_w_id, min(ol_quantity) as min_qty from order_line where ol_amount < 700 group by ol_w_id order by min_qty;
select ol_d_id, count(*) as cnt from order_line where ol_delivery_d > '2025-02-01 00:00:00' group by ol_d_id order by cnt desc;
select c_id, max(c_balance) as max_balance from customer where c_balance > 5000 group by c_id order by max_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'BC' group by c_state order by min_balance;
select o_entry_d, avg(o_ol_cnt) as avg_cnt from orders where o_entry_d > '2025-01-10 00:00:00' group by o_entry_d order by avg_cnt desc;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity > 350 group by s_w_id order by sum_qty desc;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 80 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'JAPAN' group by su.s_suppkey order by supp_count desc;
select i_id, max(i_price) as max_price from item where i_price > 4000 group by i_id order by max_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 20 group by n_name order by nation_sum desc;
select r_name, max(n_nationkey) as max_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 10 group by r_name order by max_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 500 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 200 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2025-02-10 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 3500 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'GC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2025-01-15 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 160 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 90 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 1200 group by su.s_suppkey order by avg_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 60 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 18 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 9 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 1000 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 180 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2025-02-15 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 5500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'K%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2025-02-10 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 180 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 100 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 1400 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price > 5000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 15 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 15 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount > 550 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity < 200 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2025-02-20 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance < 2000 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'BC' group by c_state order by total_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2024-11-20 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 600 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 55 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 700 group by su.s_suppkey order by total_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 80 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 16 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 11 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 1200 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 200 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2025-02-25 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 6500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'K%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2025-02-10 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 180 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt < 115 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 1800 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price > 5000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 18 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 17 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 600 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity > 200 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d < '2025-03-01 00:00:00' group by ol_d_id order by avg_amount;
select c_id, min(c_balance) as min_balance from customer where c_balance > 4000 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'L%' group by c_state order by sum_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2024-12-20 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 400 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 120 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 4000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price > 500 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 14 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 10 group by r_name order by min_nation desc; 
select ol_number, sum(ol_amount) as sum_amount from order_line where ol_quantity < 300 group by ol_number order by sum_amount desc;
select ol_w_id, min(ol_quantity) as min_qty from order_line where ol_amount > 800 group by ol_w_id order by min_qty;
select ol_d_id, count(*) as cnt from order_line where ol_delivery_d < '2025-03-01 00:00:00' group by ol_d_id order by cnt desc;
select c_id, max(c_balance) as max_balance from customer where c_balance < 6000 group by c_id order by max_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'GC' group by c_state order by min_balance;
select o_entry_d, avg(o_ol_cnt) as avg_cnt from orders where o_entry_d > '2025-02-20 00:00:00' group by o_entry_d order by avg_cnt desc;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity > 450 group by s_w_id order by sum_qty desc;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 130 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'BRAZIL' group by su.s_suppkey order by supp_count desc;
select i_id, min(i_price) as min_price from item where i_price > 150 group by i_id order by min_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 25 group by n_name order by nation_sum desc;
select r_name, max(n_nationkey) as max_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 12 group by r_name order by max_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 600 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 250 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2025-03-10 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 4500 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'BC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2025-02-25 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 220 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 110 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 1600 group by su.s_suppkey order by avg_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price > 6000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 20 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 20 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount > 700 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity < 300 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2025-03-15 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance < 2200 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'GC' group by c_state order by total_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2025-01-20 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 700 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 120 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 900 group by su.s_suppkey order by total_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 100 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 20 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 13 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 1400 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 220 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2025-03-20 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 7500 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'M%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2025-03-01 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 200 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt < 115 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 1800 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price > 5000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 22 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 22 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 800 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity > 300 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d < '2025-03-25 00:00:00' group by ol_d_id order by avg_amount;
select c_id, min(c_balance) as min_balance from customer where c_balance > 5000 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'N%' group by c_state order by sum_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2025-01-30 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 500 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 140 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 6000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price > 600 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 18 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 14 group by r_name order by min_nation desc; 
select ol_number, sum(ol_amount) as sum_amount from order_line where ol_quantity > 600 group by ol_number order by sum_amount desc;
select ol_w_id, min(ol_quantity) as min_qty from order_line where ol_amount > 1200 group by ol_w_id order by min_qty;
select ol_d_id, count(*) as cnt from order_line where ol_delivery_d < '2025-05-01 00:00:00' group by ol_d_id order by cnt desc;
select c_id, max(c_balance) as max_balance from customer where c_balance < 12000 group by c_id order by max_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'BC' group by c_state order by min_balance;
select o_entry_d, avg(o_ol_cnt) as avg_cnt from orders where o_entry_d > '2025-04-20 00:00:00' group by o_entry_d order by avg_cnt desc;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity > 800 group by s_w_id order by sum_qty desc;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 250 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'CANADA' group by su.s_suppkey order by supp_count desc;
select i_id, min(i_price) as min_price from item where i_price > 200 group by i_id order by min_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 50 group by n_name order by nation_sum desc;
select r_name, max(n_nationkey) as max_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 25 group by r_name order by max_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 1200 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 700 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2025-05-10 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 10000 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'GC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2025-04-25 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 400 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 200 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 3000 group by su.s_suppkey order by avg_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price > 10000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 40 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 50 group by r_name order by avg_nation desc; 
select ol_number, sum(ol_amount) as sum_amount from order_line where ol_quantity > 1000 group by ol_number order by sum_amount desc;
select ol_w_id, min(ol_quantity) as min_qty from order_line where ol_amount > 2000 group by ol_w_id order by min_qty;
select ol_d_id, count(*) as cnt from order_line where ol_delivery_d < '2025-05-15 00:00:00' group by ol_d_id order by cnt desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 15000 group by c_id order by min_balance;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'BC' group by c_state order by total_balance desc;
select ol_number, min(ol_quantity) as min_qty from order_line where ol_amount > 1500 group by ol_number order by min_qty;
select ol_w_id, max(ol_amount) as max_amount from order_line where ol_quantity < 200 group by ol_w_id order by max_amount desc;
select ol_d_id, avg(ol_quantity) as avg_qty from order_line where ol_delivery_d > '2025-06-01 00:00:00' group by ol_d_id order by avg_qty;
select c_id, sum(c_balance) as total_balance from customer where c_balance > 25000 group by c_id order by total_balance desc;
select c_state, min(c_balance) as min_balance from customer where c_credit = 'GC' group by c_state order by min_balance;
select o_entry_d, count(*) as cnt from orders where o_entry_d > '2025-06-01 00:00:00' group by o_entry_d order by cnt desc;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 2000 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 600 group by s_i_id order by min_orders;
select su.s_suppkey, count(*) as supp_count from supplier su join nation n on su.s_nationkey = n.n_nationkey where n.n_name = 'MEXICO' group by su.s_suppkey order by supp_count desc;
select i_id, min(i_price) as min_price from item where i_price > 1000 group by i_id order by min_price;
select n_name, sum(n_nationkey) as nation_sum from nation where n_nationkey < 200 group by n_name order by nation_sum desc;
select r_name, max(n_nationkey) as max_nation from region join nation on r_regionkey = n_regionkey where n_nationkey > 100 group by r_name order by max_nation desc;
select ol_number, avg(ol_amount) as avg_amount from order_line where ol_amount > 3000 group by ol_number order by avg_amount desc;
select ol_w_id, count(*) as count_orders from order_line where ol_quantity > 2000 group by ol_w_id order by count_orders desc;
select ol_d_id, sum(ol_amount) as sum_amount from order_line where ol_delivery_d < '2025-06-10 00:00:00' group by ol_d_id order by sum_amount desc;
select c_id, min(c_balance) as min_balance from customer where c_balance > 30000 group by c_id order by min_balance;
select c_state, avg(c_balance) as avg_balance from customer where c_credit = 'BC' group by c_state order by avg_balance;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d < '2025-06-15 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 2000 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 700 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 10000 group by su.s_suppkey order by avg_acctbal desc;
select i_id, max(i_price) as max_price from item where i_price > 30000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 100 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 200 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount > 4000 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity < 2000 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d > '2025-06-15 00:00:00' group by ol_d_id order by avg_amount;
select c_id, count(*) as cnt from customer where c_balance < 4000 group by c_id order by cnt desc;
select c_state, sum(c_balance) as total_balance from customer where c_credit = 'GC' group by c_state order by total_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d > '2025-05-20 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, sum(s_quantity) as sum_qty from stock where s_quantity < 2000 group by s_w_id order by sum_qty desc;
select s_i_id, avg(s_order_cnt) as avg_orders from stock where s_order_cnt > 800 group by s_i_id order by avg_orders;
select su.s_suppkey, sum(su.s_acctbal) as total_acctbal from supplier su where su.s_acctbal < 20000 group by su.s_suppkey order by total_acctbal desc;
select i_id, min(i_price) as min_price from item where i_price < 2000 group by i_id order by min_price;
select n_name, count(*) as nation_count from nation where n_nationkey < 300 group by n_name order by nation_count desc;
select r_name, sum(n_nationkey) as nation_sum from region join nation on r_regionkey = n_regionkey where n_nationkey > 200 group by r_name order by nation_sum desc;
select ol_number, max(ol_amount) as max_amount from order_line where ol_amount < 4000 group by ol_number order by max_amount desc;
select ol_w_id, avg(ol_quantity) as avg_qty from order_line where ol_quantity < 2000 group by ol_w_id order by avg_qty;
select ol_d_id, min(ol_amount) as min_amount from order_line where ol_delivery_d > '2025-06-20 00:00:00' group by ol_d_id order by min_amount;
select c_id, sum(c_balance) as sum_balance from customer where c_balance < 25000 group by c_id order by sum_balance desc;
select c_state, count(*) as state_count from customer where c_state like 'V%' group by c_state order by state_count desc;
select o_entry_d, max(o_ol_cnt) as max_cnt from orders where o_entry_d > '2025-06-01 00:00:00' group by o_entry_d order by max_cnt desc;
select s_w_id, min(s_quantity) as min_qty from stock where s_quantity < 3000 group by s_w_id order by min_qty;
select s_i_id, sum(s_order_cnt) as total_orders from stock where s_order_cnt > 900 group by s_i_id order by total_orders desc;
select su.s_suppkey, avg(su.s_acctbal) as avg_acctbal from supplier su where su.s_acctbal > 20000 group by su.s_suppkey order by avg_acctbal;
select i_id, max(i_price) as max_price from item where i_price < 30000 group by i_id order by max_price;
select n_name, min(n_nationkey) as min_nation from nation where n_nationkey > 200 group by n_name order by min_nation;
select r_name, avg(n_nationkey) as avg_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 300 group by r_name order by avg_nation desc;
select ol_number, count(*) as cnt from order_line where ol_amount < 4000 group by ol_number order by cnt desc;
select ol_w_id, sum(ol_quantity) as total_qty from order_line where ol_quantity > 2000 group by ol_w_id order by total_qty desc;
select ol_d_id, avg(ol_amount) as avg_amount from order_line where ol_delivery_d < '2025-06-25 00:00:00' group by ol_d_id order by avg_amount;
select c_id, min(c_balance) as min_balance from customer where c_balance > 35000 group by c_id order by min_balance;
select c_state, sum(c_balance) as sum_balance from customer where c_state like 'W%' group by c_state order by sum_balance desc;
select o_entry_d, min(o_ol_cnt) as min_cnt from orders where o_entry_d < '2025-05-30 00:00:00' group by o_entry_d order by min_cnt;
select s_w_id, avg(s_quantity) as avg_qty from stock where s_quantity > 4000 group by s_w_id order by avg_qty;
select s_i_id, min(s_order_cnt) as min_orders from stock where s_order_cnt > 1200 group by s_i_id order by min_orders;
select su.s_suppkey, max(su.s_acctbal) as max_acctbal from supplier su where su.s_acctbal > 30000 group by su.s_suppkey order by max_acctbal desc;
select i_id, avg(i_price) as avg_price from item where i_price > 2000 group by i_id order by avg_price desc;
select n_name, count(*) as nation_count from nation where n_nationkey > 100 group by n_name order by nation_count desc;
select r_name, min(n_nationkey) as min_nation from region join nation on r_regionkey = n_regionkey where n_nationkey < 200 group by r_name order by min_nation desc;