| repo_id | repo_name          | owner_id | owner_login | owner_is_org | primary_language | license | size | stars | forks | parent_repo_id | is_fork | is_archived | is_deleted | latest_released_at  | pushed_at           | created_at          | updated_at          | refreshed_at        | description |
+---------+--------------------+----------+-------------+--------------+------------------+---------+------+-------+-------+----------------+---------+-------------+------------+---------------------+---------------------+---------------------+---------------------+---------------------+-------------+
|       1 | mojombo/grit       |        1 | mojombo     |            0 | NULL             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|      27 | rubinius/rubinius  |   317747 | rubinius    |            1 | C                | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|      28 | mojombo/god        |        1 | mojombo     |            0 | Ruby             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|      48 | Caged/microsis     |       25 | Caged       |            0 | NULL             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|      68 | macournoyer/thin   |       22 | macournoyer |            0 | Ruby             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|     119 | jnewland/gsa-feeds |       47 | jnewland    |            0 | Ruby             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|     130 | ruby-git/ruby-git  | 30619330 | ruby-git    |            1 | Ruby             | mit     |  978 |  1654 |   508 |           NULL |       0 |           0 |          0 | 2022-08-18 17:44:01 | 2022-09-01 00:37:46 | 2008-01-27 17:23:23 | 2022-08-24 18:23:49 | 2022-09-01 19:53:03 | NULL        |
|     142 | abhay/calais       |       75 | abhay       |            0 | NULL             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|     162 | webs/irccat        |       86 | webs        |            0 | NULL             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
|     165 | sr/git-wiki        |       90 | sr          |            0 | Ruby             | NULL    | NULL |  NULL |  NULL |           NULL |       0 |           0 |          0 | NULL                | NULL                | NULL                | NULL                | NULL                | NULL        |
+---------+--------------------+----------+-------------+--------------+------------------+---------+------+-------+-------+----------------+---------+-------------+------------+---------------------+---------------------+---------------------+---------------------+---------------------+-------------+