import re

# 示例输入：查询计划的字符串
sql_plan = """
| id                                                | estRows       | actRows | task      | access object    | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                          | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | memory    | disk    |
+---------------------------------------------------+---------------+---------+-----------+------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
| Sort_28                                           | 1.00          | 0       | root      |                  | time:1.43s, loops:1, RU:7691.608381                                                                                                                                                                                                                                                                                                                                                                                                                     | Column#78:desc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | 0 Bytes   | 0 Bytes |
| └─Projection_30                                   | 1.00          | 0       | root      |                  | time:1.43s, loops:1, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                    | ch.nation.n_name, Column#78                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 28.4 KB   | N/A     |
|   └─HashAgg_31                                    | 1.00          | 0       | root      |                  | time:1.43s, loops:1, partial_worker:{wall_time:1.425332635s, concurrency:5, task_num:0, tot_wait:7.126458554s, tot_exec:0s, tot_time:7.126468447s, max:1.425300028s, p95:1.425300028s}, final_worker:{wall_time:1.425350994s, concurrency:5, task_num:5, tot_wait:6.535µs, tot_exec:225ns, tot_time:7.126600909s, max:1.425323368s, p95:1.425323368s}                                                                                                   | group by:ch.nation.n_name, funcs:sum(ch.order_line.ol_amount)->Column#78, funcs:firstrow(ch.nation.n_name)->ch.nation.n_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 47.4 KB   | 0 Bytes |
|     └─Projection_32                               | 5652.64       | 0       | root      |                  | time:1.43s, loops:1, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                      | ch.order_line.ol_amount, ch.nation.n_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 20.2 KB   | N/A     |
|       └─HashJoin_34                               | 5652.64       | 0       | root      |                  | time:1.43s, loops:1, build_hash_table:{total:657.6ms, fetch:657.6ms, build:9.29µs}                                                                                                                                                                                                                                                                                                                                                                      | inner join, equal:[eq(ch.nation.n_nationkey, ch.supplier.s_nationkey) eq(ch.nation.n_nationkey, Column#97)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 2.21 KB   | 0 Bytes |
|         ├─HashJoin_36(Build)                      | 0.01          | 5       | root      |                  | time:657.6ms, loops:2, build_hash_table:{total:657.3ms, fetch:657.3ms, build:9.5µs}, probe:{concurrency:5, total:3.29s, max:657.4ms, probe:67.1µs, fetch and wait:3.29s}                                                                                                                                                                                                                                                                                | inner join, equal:[eq(ch.region.r_regionkey, ch.nation.n_regionkey)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 25.7 KB   | 0 Bytes |
|         │ ├─TableReader_39(Build)                 | 0.01          | 1       | root      |                  | time:657.2ms, loops:2, cop_task: {num: 1, max: 657.9ms, proc_keys: 5, tot_proc: 440.2ms, tot_wait: 688.2µs, copr_cache_hit_ratio: 0.00, build_task_duration: 10.2µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:1, total_time:657.8ms}}                                                                                                                                                                                                        | data:Selection_38                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | 324 Bytes | N/A     |
|         │ │ └─Selection_38                        | 0.01          | 1       | cop[tikv] |                  | tikv_task:{time:440ms, loops:1}, scan_detail: {total_process_keys: 5, total_process_keys_size: 579, total_keys: 6, get_snapshot_time: 618µs, rocksdb: {key_skipped_count: 5, block: {cache_hit_count: 4}}}, time_detail: {total_process_time: 440.2ms, total_suspend_time: 49µs, total_wait_time: 688.2µs, tikv_wall_time: 655.6ms}                                                                                                                     | eq(ch.region.r_name, "EUROPE")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | N/A       | N/A     |
|         │ │   └─TableFullScan_37                  | 5.00          | 5       | cop[tikv] | table:region     | tikv_task:{time:0s, loops:1}                                                                                                                                                                                                                                                                                                                                                                                                                            | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | N/A       | N/A     |
|         │ └─TableReader_41(Probe)                 | 25.00         | 25      | root      | partition:all    | time:2.74ms, loops:2, cop_task: {num: 4, max: 3.42ms, min: 3.35ms, avg: 3.38ms, p95: 3.42ms, tot_proc: 29.4µs, tot_wait: 2.34ms, copr_cache_hit_ratio: 1.00, build_task_duration: 10.5µs, max_distsql_concurrency: 4}, rpc_info:{Cop:{num_rpc:4, total_time:13.4ms}}                                                                                                                                                                                    | data:TableFullScan_40                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1.15 KB   | N/A     |
|         │   └─TableFullScan_40                    | 25.00         | 25      | cop[tikv] | table:nation     | tikv_task:{proc max:191ms, min:191ms, avg: 191ms, p80:191ms, p95:191ms, iters:4, tasks:4}, scan_detail: {get_snapshot_time: 2.01ms, rocksdb: {block: {}}}, time_detail: {total_process_time: 29.4µs, total_wait_time: 2.34ms, tikv_wall_time: 3.86ms}                                                                                                                                                                                                   | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | N/A       | N/A     |
|         └─Projection_42(Probe)                    | 628467733.17  | 0       | root      |                  | time:1.42s, loops:1, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                      | ch.order_line.ol_amount, ch.supplier.s_nationkey, ascii(substr(ch.customer.c_state, 1, 1))->Column#97                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 22.7 KB   | N/A     |
|           └─Projection_43                         | 628467733.17  | 0       | root      |                  | time:1.42s, loops:1, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                      | ch.customer.c_state, ch.order_line.ol_amount, ch.supplier.s_nationkey                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 23.9 KB   | N/A     |
|             └─HashJoin_45                         | 628467733.17  | 0       | root      |                  | time:1.42s, loops:1, build_hash_table:{total:13.7ms, fetch:4.51ms, build:9.19ms}, probe:{concurrency:5, total:7.12s, max:1.42s, probe:412.1ms, fetch and wait:6.71s}                                                                                                                                                                                                                                                                                    | inner join, equal:[eq(ch.supplier.s_suppkey, Column#79) eq(ch.supplier.s_suppkey, Column#80) eq(ch.supplier.s_suppkey, Column#81) eq(ch.supplier.s_suppkey, Column#82) eq(ch.supplier.s_suppkey, Column#83) eq(ch.supplier.s_suppkey, Column#84) eq(ch.supplier.s_suppkey, Column#85) eq(ch.supplier.s_nationkey, Column#86) eq(ch.supplier.s_suppkey, Column#87)]                                                                                                                                                                                                                                                                                            | 888.8 KB  | 0 Bytes |
|               ├─TableReader_47(Build)             | 10000.00      | 10000   | root      | partition:all    | time:8.04ms, loops:11, cop_task: {num: 16, max: 3.12ms, min: 1.92ms, avg: 2.52ms, p95: 3.12ms, max_proc_keys: 992, p95_proc_keys: 992, tot_proc: 23.9ms, tot_wait: 1.38ms, copr_cache_hit_ratio: 0.00, build_task_duration: 9.75µs, max_distsql_concurrency: 4}, rpc_info:{Cop:{num_rpc:16, total_time:39.9ms}}                                                                                                                                         | data:TableFullScan_46                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 38.6 KB   | N/A     |
|               │ └─TableFullScan_46                | 10000.00      | 10000   | cop[tikv] | table:supplier   | tikv_task:{proc max:2ms, min:1ms, avg: 1.38ms, p80:2ms, p95:2ms, iters:68, tasks:16}, scan_detail: {total_process_keys: 10000, total_process_keys_size: 1865339, total_keys: 10016, get_snapshot_time: 480.8µs, rocksdb: {key_skipped_count: 10000, block: {cache_hit_count: 126}}}, time_detail: {total_process_time: 23.9ms, total_suspend_time: 288µs, total_wait_time: 1.38ms, total_kv_read_wall_time: 22ms, tikv_wall_time: 28.5ms}               | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
|               └─Projection_48(Probe)              | 7493293190.31 | 1250435 | root      |                  | time:1.42s, loops:1224, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                   | ch.customer.c_state, ch.order_line.ol_amount, mod(mul(ch.order_line.ol_w_id, ch.order_line.ol_i_id), 10000)->Column#79, mod(mul(ch.orders.o_w_id, ch.order_line.ol_i_id), 10000)->Column#80, mod(mul(ch.customer.c_w_id, ch.order_line.ol_i_id), 10000)->Column#81, mod(mul(ch.stock.s_w_id, ch.order_line.ol_i_id), 10000)->Column#82, mod(mul(ch.order_line.ol_w_id, ch.stock.s_i_id), 10000)->Column#83, mod(mul(ch.orders.o_w_id, ch.stock.s_i_id), 10000)->Column#84, mod(mul(ch.customer.c_w_id, ch.stock.s_i_id), 10000)->Column#85, ascii(substr(ch.customer.c_state, 1, 1))->Column#86, mod(mul(ch.stock.s_w_id, ch.stock.s_i_id), 10000)->Column#87 | 1.17 MB   | N/A     |
|                 └─HashJoin_49                     | 7493293190.31 | 1250435 | root      |                  | time:1.35s, loops:1224, build_hash_table:{total:1.06s, fetch:892.9ms, build:164ms}, probe:{concurrency:5, total:7.11s, max:1.42s, probe:1.5s, fetch and wait:5.61s}                                                                                                                                                                                                                                                                                     | inner join, equal:[eq(ch.order_line.ol_w_id, ch.stock.s_w_id) eq(ch.order_line.ol_i_id, ch.stock.s_i_id)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 30.2 MB   | 0 Bytes |
|                   ├─TableReader_90(Build)         | 449998.00     | 400000  | root      | partition:all    | time:906.1ms, loops:396, cop_task: {num: 40, max: 546.5ms, min: 2.33ms, avg: 87.9ms, p95: 514.6ms, max_proc_keys: 33760, p95_proc_keys: 33760, tot_proc: 3.46s, tot_wait: 6.39ms, copr_cache_hit_ratio: 0.00, build_task_duration: 13µs, max_distsql_concurrency: 4}, rpc_info:{Cop:{num_rpc:40, total_time:3.52s}}                                                                                                                                     | data:TableFullScan_89                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 1.03 MB   | N/A     |
|                   │ └─TableFullScan_89            | 449998.00     | 400000  | cop[tikv] | table:stock      | tikv_task:{proc max:544ms, min:1ms, avg: 85.7ms, p80:102ms, p95:511ms, iters:548, tasks:40}, scan_detail: {total_process_keys: 400000, total_process_keys_size: 148139552, total_keys: 400040, get_snapshot_time: 4.1ms, rocksdb: {key_skipped_count: 799960, block: {cache_hit_count: 5311}}}, time_detail: {total_process_time: 3.46s, total_suspend_time: 3.16ms, total_wait_time: 6.39ms, total_kv_read_wall_time: 3.43s, tikv_wall_time: 3.48s}    | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
|                   └─HashJoin_51(Probe)            | 1985417669.26 | 1250435 | root      |                  | time:1.02s, loops:1225, build_hash_table:{total:1.02s, fetch:740ms, build:278.6ms}, probe:{concurrency:5, total:7.1s, max:1.42s, probe:700.2ms, fetch and wait:6.4s}                                                                                                                                                                                                                                                                                    | inner join, equal:[eq(ch.orders.o_id, ch.order_line.ol_o_id) eq(ch.orders.o_w_id, ch.order_line.ol_w_id) eq(ch.orders.o_d_id, ch.order_line.ol_d_id)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 114.5 MB  | 0 Bytes |
|                     ├─TableReader_88(Build)       | 1250435.00    | 1250435 | root      |                  | time:748.4ms, loops:1225, cop_task: {num: 41, max: 71.5ms, min: 2.34ms, avg: 37.2ms, p95: 61.9ms, max_proc_keys: 50144, p95_proc_keys: 50144, tot_proc: 1.28s, tot_wait: 6.1ms, copr_cache_hit_ratio: 0.00, build_task_duration: 10µs, max_distsql_concurrency: 2}, rpc_info:{Cop:{num_rpc:41, total_time:1.52s}}                                                                                                                                       | data:TableFullScan_87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 6.89 MB   | N/A     |
|                     │ └─TableFullScan_87          | 1250435.00    | 1250435 | cop[tikv] | table:order_line | tikv_task:{proc max:45ms, min:0s, avg: 24.7ms, p80:39ms, p95:42ms, iters:1384, tasks:41}, scan_detail: {total_process_keys: 1250435, total_process_keys_size: 133908983, total_keys: 1250476, get_snapshot_time: 3.21ms, rocksdb: {key_skipped_count: 1250435, block: {cache_hit_count: 4781}}}, time_detail: {total_process_time: 1.28s, total_suspend_time: 2.69ms, total_wait_time: 6.1ms, total_kv_read_wall_time: 1.01s, tikv_wall_time: 1.3s}     | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
|                     └─HashJoin_81(Probe)          | 5001520.00    | 125038  | root      |                  | time:666.4ms, loops:124, build_hash_table:{total:654.9ms, fetch:608.8ms, build:46.1ms}, probe:{concurrency:5, total:7.02s, max:1.41s, probe:126.9ms, fetch and wait:6.89s}                                                                                                                                                                                                                                                                              | inner join, equal:[eq(ch.customer.c_id, ch.orders.o_c_id) eq(ch.customer.c_w_id, ch.orders.o_w_id) eq(ch.customer.c_d_id, ch.orders.o_d_id)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 11.0 MB   | 0 Bytes |
|                       ├─TableReader_83(Build)     | 123351.00     | 120000  | root      |                  | time:612.3ms, loops:119, cop_task: {num: 10, max: 484.1ms, min: 4.23ms, avg: 64.1ms, p95: 484.1ms, max_proc_keys: 47840, p95_proc_keys: 47840, tot_proc: 614.9ms, tot_wait: 1.92ms, copr_cache_hit_ratio: 0.00, build_task_duration: 3.87µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:10, total_time:640.6ms}}                                                                                                                               | data:TableFullScan_82                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 2.65 MB   | N/A     |
|                       │ └─TableFullScan_82        | 123351.00     | 120000  | cop[tikv] | table:customer   | tikv_task:{proc max:70ms, min:1ms, avg: 19.7ms, p80:43ms, p95:70ms, iters:156, tasks:10}, scan_detail: {total_process_keys: 120000, total_process_keys_size: 76589385, total_keys: 120010, get_snapshot_time: 1.18ms, rocksdb: {key_skipped_count: 239990, block: {cache_hit_count: 2576}}}, time_detail: {total_process_time: 614.9ms, total_suspend_time: 785.2µs, total_wait_time: 1.92ms, total_kv_read_wall_time: 197ms, tikv_wall_time: 620.1ms}  | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
|                       └─TableReader_86(Probe)     | 125038.00     | 125038  | root      |                  | time:69.9ms, loops:124, cop_task: {num: 11, max: 54.5ms, min: 3.1ms, avg: 17.8ms, p95: 54.5ms, max_proc_keys: 50144, p95_proc_keys: 50144, tot_proc: 166.5ms, tot_wait: 2.41ms, copr_cache_hit_ratio: 0.00, build_task_duration: 2.81µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:11, total_time:195.8ms}}                                                                                                                                   | data:Selection_85                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | 3.21 MB   | N/A     |
|                         └─Selection_85            | 125038.00     | 125038  | cop[tikv] |                  | tikv_task:{proc max:43ms, min:2ms, avg: 14ms, p80:22ms, p95:43ms, iters:165, tasks:11}, scan_detail: {total_process_keys: 125038, total_process_keys_size: 9096709, total_keys: 125049, get_snapshot_time: 1.46ms, rocksdb: {key_skipped_count: 125038, block: {cache_hit_count: 371}}}, time_detail: {total_process_time: 166.5ms, total_suspend_time: 629µs, total_wait_time: 2.41ms, total_kv_read_wall_time: 144ms, tikv_wall_time: 173.1ms}        | ge(ch.orders.o_entry_d, 2024-10-23 17:00:00.000000), not(isnull(ch.orders.o_c_id))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | N/A       | N/A     |
|                           └─TableFullScan_84      | 125038.00     | 125038  | cop[tikv] | table:orders     | tikv_task:{proc max:39ms, min:2ms, avg: 13.1ms, p80:22ms, p95:39ms, iters:165, tasks:11}                                                                                                                                                                                                                                                                                                                                                                | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
"""

# 解析 SQL 计划的每一行
lines = sql_plan.strip().split('\n')

# 存储每行的相关数据
operators = []

# 正则表达式用于匹配算子的 ID 和访问的表
#pattern_operator = r"└─(\S+)"
pattern_operator = r"(└─|├─)(\S+)"
pattern_table = r"table:(\S+)"

# 遍历每一行，查找符合条件的算子
for i, line in enumerate(lines):
    operator_match = re.search(pattern_operator, line)
    if operator_match:
        #print(i)
        operator_name = operator_match.group(2)
        #print(operator_name)

        # 截断算子名称中的 "_" 及其后的部分
        operator_name = operator_name.split("_")[0]        
        
        # 如果算子的名称包含 'TableFullScan'，记录这一行
        if "TableFullScan" in operator_name:
            # 查找这一行中访问的表
            #print("yes")
            table_match = re.search(pattern_table, line)
            table_name = table_match.group(1) if table_match else None
            
            # 找到上一行的算子名称
            previous_operator = lines[i - 1] if i - 1 >= 0 else None
            previous_operator_match = re.search(pattern_operator, previous_operator)
            previous_operator_name = previous_operator_match.group(2) if previous_operator_match else "N/A"

            # 截断上一行算子名称中的 "_" 及其后的部分
            previous_operator_name = previous_operator_name.split("_")[0]            
            
            # 记录当前算子及其上一个算子的相关信息
            operators.append({
                'operator_name': operator_name,
                'table_name': table_name,
                'previous_operator': previous_operator_name
            })

# 输出所有的算子名称及其对应的表
for operator in operators:
    print(f"Operator: {operator['operator_name']}, Table: {operator['table_name']}, Previous Operator: {operator['previous_operator']}")
